PROJETO FINAL - ANALISE DE MANUTENÇÃO DE MAQUINAS PARA FABRICAS

Fase 1 — Análise Exploratória (EDA)

1.1 Importar Bibliotecas

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
#preconfiguração de visualização
pd.set_option('display.float_format', '{:.2f}'.format)

1.2 Leitura da Base de dados

In [25]:
df_ler = pd.read_csv('data/manutencao_preditiva.csv')
df_ler.head()

,udi,id_produto,tipo,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,falha_maquina,falha_twf,falha_hdf,falha_pwf,falha_osf,falha_rnf
0,1,M14860,M,298.10,308.60,1551.00,42.80,0,0,0,0,0,0,0
1,2,L47181,L,298.20,308.70,1408.00,46.30,3,0,0,0,0,0,0
2,3,L47182,L,298.10,308.50,1498.00,49.40,5,0,0,0,0,0,0
3,4,L47183,L,NaN,NaN,NaN,NaN,7,0,0,0,0,0,0
4,5,L47184,L,298.20,308.70,1408.00,40.00,9,0,0,0,0,0,0

In [21]:
df_ler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   udi                      10000 non-null  int64
 1   id_produto               10000 non-null  object
 2   tipo                     10000 non-null  object
 3   temperatura_ar_k         9500 non-null   float64
 4   temperatura_processo_k   9500 non-null   float64
 5   velocidade_rotacao_rpm   9500 non-null   float64
 6   torque_nm                9500 non-null   float64
 7   desgaste_ferramenta_min  10000 non-null  int64
 8   falha_maquina            10000 non-null  int64
 9   falha_twf                10000 non-null  int64
 10  falha_hdf                10000 non-null  int64
 11  falha_pwf                10000 non-null  int64
 12  falha_osf                10000 non-null  int64
 13  falha_rnf                10000 non-null  int64
dtypes: float64(4), int64(8), object(2)
memory usage: 1.1+ MB

In [22]:
df_ler.describe()

,udi,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,falha_maquina,falha_twf,falha_hdf,falha_pwf,falha_osf,falha_rnf
count,10000.00,9500.00,9500.00,9500.00,9500.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00
mean,5000.50,300.00,310.00,1539.25,39.97,107.95,0.03,0.00,0.01,0.01,0.01,0.00
std,2886.90,2.00,1.49,180.27,10.00,63.65,0.18,0.07,0.11,0.10,0.10,0.04
min,1.00,295.30,305.70,1168.00,3.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,2500.75,298.30,308.80,1423.00,33.10,53.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,5000.50,300.10,310.10,1504.00,40.10,108.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,7500.25,301.50,311.10,1613.00,46.70,162.00,0.00,0.00,0.00,0.00,0.00,0.00
max,10000.00,304.50,313.80,2886.00,76.60,253.00,1.00,1.00,1.00,1.00,1.00,1.00

1.3 Analise inicial

Como podemos ver acima o dataset possui 10000 linhas e 14 colunas composta por identificadores, atributos de sensores e a variável alvo (falha__maquina). 
nas colunas (temperatura_ar_k, temperatura_processo_k, velocidade_rotacao_rpm e torque_nm) temos valores ausentes que representam 5% dos dados totais e precisam ser tratados na limpeza.

a variável alvo (falha__maquina) só tem 3% dos registros que representam falha classe1 os outros 97% de registros representam operação normal classe0

as variaveis (temperatura_ar_k, temperatura_processo_k, velocidade_rotacao_rpm e torque_nm) tem valores em escalas muito distintas isso precisa ser tratado para o uso do KNN

Quanto à distribuição, as temperaturas apresentam média e mediana praticamente iguais, enquanto velocidade_rotacao_rpm tem média maior que a mediana e valores máximos muito acima do 3º quartil.